# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_qbin_wrappers", use_symbols = TRUE, package_name = "qbin")

#' @usage NULL
#' @useDynLib qbin, .registration = TRUE
NULL

quadbin_to_ints <- function(x) .Call(wrap__quadbin_to_ints, x)

vctrs_class <- function() .Call(wrap__vctrs_class)


# nolint end
